### ISSUE TITLE
Examples/Getting Started

### ISSUE THREAD

**Issue by d4hines** [metasoarous/datview#14]
Greetings!

I'd like to start playing with DatView. Are there any examples I can use to get started? Bonus points if it also uses DatSync.

Thanks!

**Comment by d4hines** [comment]
On closer inspection, it looks like the DatSys repo _is_ what I'm looking for.

**Comment by metasoarous** [comment]
Hey @d4hines! Thanks for raising this issue.

You're correct; Datsys is really the place to go to see Datview in action at the moment. As you note, Datsys is really just an example app. There's also a branch which refactors it as a lein generator (so that you can run `lein new datsys yourapp`), but unfortunately this branch may be a little out of date (and honestly I haven't run the demo app in a while either, but @bamarco has).

Thanks again!
